server:
  port: 8089

spring:
  application:
    name: gundam-job
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: @profiles.active@
