server:
  port: 8086

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: ${NACOS_HOST:gundam-nacos}:${NACOS_PORT:8848}
      discovery:
        group: @nacos.group@
      config:
        group: @nacos.group@
  config:
    # import中有optional修饰的配置文件即使没有找到,spring boot也能够正常启动
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:common.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username: root
      password: 123456